# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 951fcde67fb73f0960625edc9c3eecc2b15510cfff580c4d4b30c5aabd9ac6fe77d438d8a64fd49a06d9c21c32d688276807bb329bb18c8a564bd58daed6c9a0

test:
  secret_key_base: 876fb889d3a7aec856205ccb4c93a6833929d39fee3e5204f870ae75123a715fce8790670d2ed3c4e01f52335adce037c392fe4e345e9c9dfb4dcfa66756fd0a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
